// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import "package:firebase_core/firebase_core.dart" show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux: // This case doesn't exist in your code
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions web = const FirebaseOptions(
    apiKey: 'AIzaSyDO7X0Zx7iQ7XIpvwbDknrm1yuspAcwmmE',
    appId: '1:269032679610:web:5c688a5e76a8391fed3a83',
    messagingSenderId: '269032679610',
    projectId: 'finalproject-70d45',
    authDomain: 'finalproject-70d45.firebaseapp.com',
    storageBucket: 'finalproject-70d45.appspot.com',
    measurementId: 'G-GJDQD6NWWG',
  );

  static FirebaseOptions android = const FirebaseOptions(
    apiKey: 'AIzaSyAnZvc6HXlry45hB7WLZRwwbyC_891TVG4',
    appId: '1:269032679610:android:670a771d85e50619ed3a83',
    messagingSenderId: '269032679610',
    projectId: 'finalproject-70d45',
    storageBucket: 'finalproject-70d45.appspot.com',
  );

  static  FirebaseOptions ios = const FirebaseOptions(
    apiKey: 'AIzaSyARdfmhDyqpaXBY3YDbXykmk2OKxMoTsdY',
    appId: '1:269032679610:ios:7120cfe405970213ed3a83',
    messagingSenderId: '269032679610',
    projectId: 'finalproject-70d45',
    storageBucket: 'finalproject-70d45.appspot.com',
    iosBundleId: 'com.example.fitnessapp',
  );

  static FirebaseOptions macos = const FirebaseOptions(
    apiKey: 'AIzaSyARdfmhDyqpaXBY3YDbXykmk2OKxMoTsdY',
    appId: '1:269032679610:ios:7120cfe405970213ed3a83',
    messagingSenderId: '269032679610',
    projectId: 'finalproject-70d45',
    storageBucket: 'finalproject-70d45.appspot.com',
    iosBundleId: 'com.example.fitnessapp',
  );

  static  FirebaseOptions windows = const FirebaseOptions(
    apiKey: 'AIzaSyDO7X0Zx7iQ7XIpvwbDknrm1yuspAcwmmE',
    appId: '1:269032679610:web:7d754a73886e6d14ed3a83',
    messagingSenderId: '269032679610',
    projectId: 'finalproject-70d45',
    authDomain: 'finalproject-70d45.firebaseapp.com',
    storageBucket: 'finalproject-70d45.appspot.com',
    measurementId: 'G-QEGENWVPK2',
  );
}
